[book]
authors = ["CJ Burkey"]
language = "en"
multilingual = false
src = "src"
title = "ClaimChunk"
description = "A site detailing how to use the SpigotAPI plugin ClaimChunk"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/cjburkey01/ClaimChunk"
edit-url-template = "https://github.com/cjburkey01/claimchunk-site/edit/main/{path}"
additional-js = []
additional-css = ["src/css/downloads.css"]
no-section-label = true

[output.html.print]
enable = false
