name: github pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install gettext
        run: |
          sudo apt update
          sudo apt install gettext

      - name: Install mdbook
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          locked: false
          tool: mdbook

      - name: Install mdbook-i18n-helpers
        uses: taiki-e/cache-cargo-install-action@v2
        # noinspection YAMLSchemaValidation
        with:
          locked: false
          tool: mdbook-i18n-helpers

      - name: Build the book
        run: sh scripts/full-build.sh

      - name: Copy CNAME
        run: cp config/CNAME book/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
